//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubjectTestProject.UI.TgaTrainingComp {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ClassificationFilters", Namespace="http://training.gov.au/services/3/", ItemName="ClassificationFilter", KeyName="Scheme", ValueName="Values")]
    [System.SerializableAttribute()]
    public class ClassificationFilters : System.Collections.Generic.Dictionary<string, string[]> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://training.gov.au/services/3/", ConfigurationName="TgaTrainingComp.ITrainingComponentService")]
    public interface ITrainingComponentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetDetails", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/GetDetailsValidationF" +
            "aultFault", Name="ValidationFault")]
        SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponent GetDetails(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetDetails", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetDetailsResponse")]
        System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponent> GetDetailsAsync(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetServerTime", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetServerTimeResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/GetServerTimeValidati" +
            "onFaultFault", Name="ValidationFault")]
        System.DateTime GetServerTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetServerTime", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetServerTimeResponse" +
            "")]
        System.Threading.Tasks.Task<System.DateTime> GetServerTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetValidationCodes", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetValidationCodesRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/GetValidationCodesVal" +
            "idationFaultFault", Name="ValidationFault")]
        SubjectTestProject.DataAccess.TgaTrainingComp.ValidationCode[] GetValidationCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetValidationCodes", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetValidationCodesRes" +
            "ponse")]
        System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.ValidationCode[]> GetValidationCodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/Search", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/SearchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/SearchValidationFault" +
            "Fault", Name="ValidationFault")]
        SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentSearchResult Search(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/Search", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/SearchResponse")]
        System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentSearchResult> SearchAsync(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/SearchByModifiedDate", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/SearchByModifiedDateR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/SearchByModifiedDateV" +
            "alidationFaultFault", Name="ValidationFault")]
        SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentSearchResult SearchByModifiedDate(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentModifiedSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/SearchByModifiedDate", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/SearchByModifiedDateR" +
            "esponse")]
        System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentSearchResult> SearchByModifiedDateAsync(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentModifiedSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/Add", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/AddResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/AddValidationFaultFau" +
            "lt", Name="ValidationFault")]
        void Add(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponent request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/Add", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponent request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/Update", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/UpdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/UpdateValidationFault" +
            "Fault", Name="ValidationFault")]
        void Update(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/Update", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/SearchDeletedByDelete" +
            "dDate", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/SearchDeletedByDelete" +
            "dDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/SearchDeletedByDelete" +
            "dDateValidationFaultFault", Name="ValidationFault")]
        SubjectTestProject.DataAccess.TgaTrainingComp.DeletedTrainingComponent[] SearchDeletedByDeletedDate(SubjectTestProject.DataAccess.TgaTrainingComp.DeletedSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/SearchDeletedByDelete" +
            "dDate", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/SearchDeletedByDelete" +
            "dDateResponse")]
        System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.DeletedTrainingComponent[]> SearchDeletedByDeletedDateAsync(SubjectTestProject.DataAccess.TgaTrainingComp.DeletedSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/Delete", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/DeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/DeleteValidationFault" +
            "Fault", Name="ValidationFault")]
        void Delete(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/Delete", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/TransferDataManager", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/TransferDataManagerRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/TransferDataManagerVa" +
            "lidationFaultFault", Name="ValidationFault")]
        void TransferDataManager(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentTransferDataManagerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/TransferDataManager", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/TransferDataManagerRe" +
            "sponse")]
        System.Threading.Tasks.Task TransferDataManagerAsync(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentTransferDataManagerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetLookup", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetLookupResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/GetLookupValidationFa" +
            "ultFault", Name="ValidationFault")]
        SubjectTestProject.DataAccess.TgaTrainingComp.Lookup[] GetLookup(SubjectTestProject.DataAccess.TgaTrainingComp.LookupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetLookup", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetLookupResponse")]
        System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.Lookup[]> GetLookupAsync(SubjectTestProject.DataAccess.TgaTrainingComp.LookupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetTaxonomyOccupation" +
            "", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetTaxonomyOccupation" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/GetTaxonomyOccupation" +
            "ValidationFaultFault", Name="ValidationFault")]
        SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentOccupation[] GetTaxonomyOccupation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetTaxonomyOccupation" +
            "", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetTaxonomyOccupation" +
            "Response")]
        System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentOccupation[]> GetTaxonomyOccupationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetTaxonomyIndustrySe" +
            "ctor", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetTaxonomyIndustrySe" +
            "ctorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/GetTaxonomyIndustrySe" +
            "ctorValidationFaultFault", Name="ValidationFault")]
        SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentIndustrySector[] GetTaxonomyIndustrySector();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetTaxonomyIndustrySe" +
            "ctor", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetTaxonomyIndustrySe" +
            "ctorResponse")]
        System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentIndustrySector[]> GetTaxonomyIndustrySectorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetAddressStates", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetAddressStatesRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/GetAddressStatesValid" +
            "ationFaultFault", Name="ValidationFault")]
        SubjectTestProject.DataAccess.TgaTrainingComp.AddressStates[] GetAddressStates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetAddressStates", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetAddressStatesRespo" +
            "nse")]
        System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.AddressStates[]> GetAddressStatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetContactRoles", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetContactRolesRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/GetContactRolesValida" +
            "tionFaultFault", Name="ValidationFault")]
        SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentContactRole[] GetContactRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetContactRoles", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetContactRolesRespon" +
            "se")]
        System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentContactRole[]> GetContactRolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetDataManagers", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetDataManagersRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/GetDataManagersValida" +
            "tionFaultFault", Name="ValidationFault")]
        SubjectTestProject.DataAccess.TgaTrainingComp.DataManager[] GetDataManagers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetDataManagers", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetDataManagersRespon" +
            "se")]
        System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.DataManager[]> GetDataManagersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetRecognitionManager" +
            "s", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetRecognitionManager" +
            "sResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/GetRecognitionManager" +
            "sValidationFaultFault", Name="ValidationFault")]
        SubjectTestProject.DataAccess.TgaTrainingComp.RecognitionManager[] GetRecognitionManagers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetRecognitionManager" +
            "s", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetRecognitionManager" +
            "sResponse")]
        System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.RecognitionManager[]> GetRecognitionManagersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetClassificationSche" +
            "mes", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetClassificationSche" +
            "mesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/GetClassificationSche" +
            "mesValidationFaultFault", Name="ValidationFault")]
        SubjectTestProject.DataAccess.TgaTrainingComp.NrtClassificationSchemeResult[] GetClassificationSchemes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetClassificationSche" +
            "mes", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetClassificationSche" +
            "mesResponse")]
        System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.NrtClassificationSchemeResult[]> GetClassificationSchemesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetClassificationPurp" +
            "oses", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetClassificationPurp" +
            "osesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SubjectTestProject.DataAccess.TgaTrainingComp.ValidationFault), Action="http://training.gov.au/services/3/ITrainingComponentService/GetClassificationPurp" +
            "osesValidationFaultFault", Name="ValidationFault")]
        SubjectTestProject.DataAccess.TgaTrainingComp.ClassificationPurpose[] GetClassificationPurposes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://training.gov.au/services/3/ITrainingComponentService/GetClassificationPurp" +
            "oses", ReplyAction="http://training.gov.au/services/3/ITrainingComponentService/GetClassificationPurp" +
            "osesResponse")]
        System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.ClassificationPurpose[]> GetClassificationPurposesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrainingComponentServiceChannel : SubjectTestProject.UI.TgaTrainingComp.ITrainingComponentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrainingComponentServiceClient : System.ServiceModel.ClientBase<SubjectTestProject.UI.TgaTrainingComp.ITrainingComponentService>, SubjectTestProject.UI.TgaTrainingComp.ITrainingComponentService {
        
        public TrainingComponentServiceClient() {
        }
        
        public TrainingComponentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrainingComponentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainingComponentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainingComponentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponent GetDetails(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentDetailsRequest request) {
            return base.Channel.GetDetails(request);
        }
        
        public System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponent> GetDetailsAsync(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentDetailsRequest request) {
            return base.Channel.GetDetailsAsync(request);
        }
        
        public System.DateTime GetServerTime() {
            return base.Channel.GetServerTime();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetServerTimeAsync() {
            return base.Channel.GetServerTimeAsync();
        }
        
        public SubjectTestProject.DataAccess.TgaTrainingComp.ValidationCode[] GetValidationCodes() {
            return base.Channel.GetValidationCodes();
        }
        
        public System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.ValidationCode[]> GetValidationCodesAsync() {
            return base.Channel.GetValidationCodesAsync();
        }
        
        public SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentSearchResult Search(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentSearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentSearchResult> SearchAsync(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentSearchRequest request) {
            return base.Channel.SearchAsync(request);
        }
        
        public SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentSearchResult SearchByModifiedDate(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentModifiedSearchRequest request) {
            return base.Channel.SearchByModifiedDate(request);
        }
        
        public System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentSearchResult> SearchByModifiedDateAsync(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentModifiedSearchRequest request) {
            return base.Channel.SearchByModifiedDateAsync(request);
        }
        
        public void Add(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponent request) {
            base.Channel.Add(request);
        }
        
        public System.Threading.Tasks.Task AddAsync(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponent request) {
            return base.Channel.AddAsync(request);
        }
        
        public void Update(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentUpdateRequest request) {
            base.Channel.Update(request);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentUpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public SubjectTestProject.DataAccess.TgaTrainingComp.DeletedTrainingComponent[] SearchDeletedByDeletedDate(SubjectTestProject.DataAccess.TgaTrainingComp.DeletedSearchRequest request) {
            return base.Channel.SearchDeletedByDeletedDate(request);
        }
        
        public System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.DeletedTrainingComponent[]> SearchDeletedByDeletedDateAsync(SubjectTestProject.DataAccess.TgaTrainingComp.DeletedSearchRequest request) {
            return base.Channel.SearchDeletedByDeletedDateAsync(request);
        }
        
        public void Delete(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentDeleteRequest request) {
            base.Channel.Delete(request);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentDeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public void TransferDataManager(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentTransferDataManagerRequest request) {
            base.Channel.TransferDataManager(request);
        }
        
        public System.Threading.Tasks.Task TransferDataManagerAsync(SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentTransferDataManagerRequest request) {
            return base.Channel.TransferDataManagerAsync(request);
        }
        
        public SubjectTestProject.DataAccess.TgaTrainingComp.Lookup[] GetLookup(SubjectTestProject.DataAccess.TgaTrainingComp.LookupRequest request) {
            return base.Channel.GetLookup(request);
        }
        
        public System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.Lookup[]> GetLookupAsync(SubjectTestProject.DataAccess.TgaTrainingComp.LookupRequest request) {
            return base.Channel.GetLookupAsync(request);
        }
        
        public SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentOccupation[] GetTaxonomyOccupation() {
            return base.Channel.GetTaxonomyOccupation();
        }
        
        public System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentOccupation[]> GetTaxonomyOccupationAsync() {
            return base.Channel.GetTaxonomyOccupationAsync();
        }
        
        public SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentIndustrySector[] GetTaxonomyIndustrySector() {
            return base.Channel.GetTaxonomyIndustrySector();
        }
        
        public System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentIndustrySector[]> GetTaxonomyIndustrySectorAsync() {
            return base.Channel.GetTaxonomyIndustrySectorAsync();
        }
        
        public SubjectTestProject.DataAccess.TgaTrainingComp.AddressStates[] GetAddressStates() {
            return base.Channel.GetAddressStates();
        }
        
        public System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.AddressStates[]> GetAddressStatesAsync() {
            return base.Channel.GetAddressStatesAsync();
        }
        
        public SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentContactRole[] GetContactRoles() {
            return base.Channel.GetContactRoles();
        }
        
        public System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.TrainingComponentContactRole[]> GetContactRolesAsync() {
            return base.Channel.GetContactRolesAsync();
        }
        
        public SubjectTestProject.DataAccess.TgaTrainingComp.DataManager[] GetDataManagers() {
            return base.Channel.GetDataManagers();
        }
        
        public System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.DataManager[]> GetDataManagersAsync() {
            return base.Channel.GetDataManagersAsync();
        }
        
        public SubjectTestProject.DataAccess.TgaTrainingComp.RecognitionManager[] GetRecognitionManagers() {
            return base.Channel.GetRecognitionManagers();
        }
        
        public System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.RecognitionManager[]> GetRecognitionManagersAsync() {
            return base.Channel.GetRecognitionManagersAsync();
        }
        
        public SubjectTestProject.DataAccess.TgaTrainingComp.NrtClassificationSchemeResult[] GetClassificationSchemes() {
            return base.Channel.GetClassificationSchemes();
        }
        
        public System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.NrtClassificationSchemeResult[]> GetClassificationSchemesAsync() {
            return base.Channel.GetClassificationSchemesAsync();
        }
        
        public SubjectTestProject.DataAccess.TgaTrainingComp.ClassificationPurpose[] GetClassificationPurposes() {
            return base.Channel.GetClassificationPurposes();
        }
        
        public System.Threading.Tasks.Task<SubjectTestProject.DataAccess.TgaTrainingComp.ClassificationPurpose[]> GetClassificationPurposesAsync() {
            return base.Channel.GetClassificationPurposesAsync();
        }
    }
}
